---
title: "Text Mining and Sentiment Analysis"
author: "Kay Mattern"
date: "3/30/2021"
output:
  html_document:
    toc: TRUE
    theme: yeti
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("striprtf")
#install.packages('DT')
#install.packages('tidytext')
#install.packages('ggwordcloud')
#install.packages('gutenbergr')
#install.packages('textdata')
#install.packages('textreadr')
# library(striprtf)
library(dplyr)
library(DT)
library(tidyverse)
library(tidytext)
library(ggwordcloud)
library(gutenbergr)
library(textdata)
library(textreadr)
```

## Cleaning the data
```{r}

# Read in Illinois txt file
il <- read_lines('illinois_articles.txt')
il

# Convert to tibble for cleaning/analysis
il <- tibble(il)

# Data Cleaning
# Function to clean all txt files
clean_article <- function(x){
  clean_txt <- x[!apply(x == "", 1, all),] %>%   x[!(x$x=="Body"),] %>%
x[!(x$x=="Link to Image"),] %>%
x[!(x$x==" "),] %>%
xl[!(x$x=="End of Document"),] %>%
x[!(x$x=="Page  of "),] %>%
x[!grepl("Length", x$x),] %>%
x[!grepl("Highlight", x$x),] %>%
x[!grepl("Copyright", x$x),] %>%
x[!grepl("Load-Date", x$x),] %>%
x[!grepl("Section", x$x),] %>%
x[!grepl("Byline", x$x),] %>%
x[!grepl("PM EDT", x$x),] %>%
x[!grepl("PM EST", x$x),] %>%
x[!grepl("AM EST", x$x),] %>%
x[!grepl("Graphic", x$x),] %>%
x[!grepl("www", x$x),]
}
clean_il <- clean_article(il)

il <- il[!apply(il == "", 1, all),]
il <- il[!(il$il=="Body"),]
il <- il[!(il$il=="Link to Image"),]
il <- il[!(il$il==" "),]
il <- il[!(il$il=="End of Document"),]
il <- il[!(il$il=="Page  of "),]
il <- il[!grepl("Length", il$il),]
il <- il[!grepl("Highlight", il$il),]
il <- il[!grepl("Copyright", il$il),]
il <- il[!grepl("Load-Date", il$il),]
il <- il[!grepl("Section", il$il),]
il <- il[!grepl("Byline", il$il),]
il <- il[!grepl("PM EDT", il$il),]
il <- il[!grepl("PM EST", il$il),]
il <- il[!grepl("AM EST", il$il),]
il <- il[!grepl("Graphic", il$il),]
il <- il[!grepl("www", il$il),]

clean_il <- il
```

## Data Preparation
```{r}
#Converting to character
clean_il$il <- as.character(clean_il$il)
il$il <- as.character(il$il )

# Preparing data for analysis
#Function
prepared_data <- function(x){
  x %>% unnest_tokens(word, x) %>%
    anti_join(stop_words) %>%
    count(word, sort=TRUE)
}
prepared_data(il)

il_counts <- il %>% unnest_tokens(word, il) %>%
  anti_join(stop_words) %>%
  count(word, sort=TRUE)

il_counts
il_counts$word <- as.factor(il_counts$word)

#Graph 
ggplot(
  data = il_counts,
  aes(x = fct_reorder(word,n),
      y = n)
  ) + 
  geom_col() + 
  coord_flip()+
  theme_light()

```

## Sentiment Analysis
```{r}

# afinn 
get_sentiments('afinn')
il_sentiment_afinn <- il_counts %>%
  inner_join(get_sentiments("afinn"))
# sentiment range plot
ggplot(data = il_sentiment_afinn, 
       aes(x=value)
        )+
  geom_histogram()+
  ggtitle("Illinois Sentiment Range")+
  theme_bw() + 
  labs(x = 'Sentiment Value', y = 'Count', title='Illinois Sentiment Range (afinn)') +
  stat_bin(bins=19)
# word cloud
ggplot(il_sentiment_afinn[1:50,], aes(label = word, size = n)
       ) +
  geom_text_wordcloud() +
  theme_bw()


# nrc 
get_sentiments('nrc')
il_sentiment_nrc <- il_counts %>% 
  inner_join(get_sentiments("nrc"))
# sentiment range plot
ggplot(data = il_sentiment_nrc, 
       aes(x=sentiment)
        )+
  geom_bar()+
  ggtitle("Illinois Sentiment Range")+
  theme_bw() + 
  labs(x = 'Sentiment', y = 'Count', title='Illinois Sentiment Range (nrc)') +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.95, hjust=1))
# word cloud
set.seed(8)
ggplot(il_sentiment_nrc[1:50,], aes(label = word, size = n)
       ) +
  geom_text_wordcloud() +
  theme_bw()

# bing
get_sentiments('bing')
il_sentiment_bing <- il_counts %>% 
  inner_join(get_sentiments("bing"))
# sentiment range plot
ggplot(data = il_sentiment_bing, 
       aes(x=sentiment, fill=sentiment)
        )+
  geom_bar()+
  ggtitle("Illinois Sentiment Range")+
  theme_bw() + 
  labs(x = 'Sentiment', y = 'Count', title='Illinois Sentiment Range (bing)') +
  scale_color_manual(values = c('red', 'green'))

# word cloud
ggplot(il_sentiment_bing[1:50,], aes(label = word, size = n)
       ) +
  geom_text_wordcloud() +
  theme_bw()



```
